# Generated by Django 4.2.4 on 2023-08-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_year", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Executor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.executor"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "executor")},
            },
        ),
        migrations.CreateModel(
            name="AlbumTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.PositiveSmallIntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albumtracks",
                        to="api.album",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence",
                        to="api.track",
                    ),
                ),
            ],
            options={
                "unique_together": {("track", "serial_number")},
            },
        ),
        migrations.AddField(
            model_name="album",
            name="executor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.executor"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="tracks",
            field=models.ManyToManyField(through="api.AlbumTrack", to="api.track"),
        ),
    ]
